import json
import os
from pathlib import Path
import shutil

REPOS_DIR = Path("C:/temp/velvet-sojourner/repos")
AUDIT_JSON = Path("C:/temp/velvet-sojourner/audit/full-audit-master.json")

def load_audit():
    with open(AUDIT_JSON, "r", encoding="utf-8") as f:
        return json.load(f)

def dockerfile_python(repo_name, frameworks):
    # Check for specific frameworks
    has_fastapi = "FastAPI" in frameworks
    has_flask = "Flask" in frameworks
    has_django = "Django" in frameworks
    has_streamlit = "Streamlit" in frameworks
    
    port = "8000"
    if has_fastapi:
        port = "8000"
    elif has_flask:
        port = "5000"
    elif has_django:
        port = "8000"
    elif has_streamlit:
        port = "8501"
    
    return f"""# Dockerfile for {repo_name}
# Auto-generated by AgentForge Audit System
FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \\
    git \\
    build-essential \\
    && rm -rf /var/lib/apt/lists/*

# Copy requirements first for better caching
COPY requirements.txt* pyproject.toml* setup.py* ./
RUN pip install --no-cache-dir -r requirements.txt 2>/dev/null || \\
    pip install --no-cache-dir -e . 2>/dev/null || \\
    echo "No requirements found, skipping"

# Copy application code
COPY . .

# Expose port
EXPOSE {port}

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \\
    CMD curl -f http://localhost:{port}/health || exit 1

# Default command (override as needed)
CMD ["python", "-m", "http.server", "{port}"]
"""

def dockerfile_node(repo_name, frameworks):
    has_nextjs = "Next.js" in frameworks
    has_react = "React" in frameworks
    
    port = "3000"
    if has_nextjs:
        port = "3000"
    
    return f"""# Dockerfile for {repo_name}
# Auto-generated by AgentForge Audit System
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm ci --only=production 2>/dev/null || npm install

# Copy source and build
COPY . .
RUN npm run build 2>/dev/null || echo "No build script"

# Production stage
FROM node:20-alpine

WORKDIR /app
COPY --from=builder /app ./

EXPOSE {port}

HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost:{port}/ || exit 1

CMD ["npm", "start"]
"""

def dockerfile_rust(repo_name):
    return f"""# Dockerfile for {repo_name}
# Auto-generated by AgentForge Audit System
FROM rust:1.75-slim AS builder

WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src ./src
RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/* ./

EXPOSE 8080
CMD ["./app"]
"""

def dockerfile_go(repo_name):
    return f"""# Dockerfile for {repo_name}
# Auto-generated by AgentForge Audit System
FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o app .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/app ./

EXPOSE 8080
CMD ["./app"]
"""

def dockerfile_cpp(repo_name):
    return f"""# Dockerfile for {repo_name}
# Auto-generated by AgentForge Audit System
FROM gcc:13 AS builder

WORKDIR /app
COPY . .
RUN make 2>/dev/null || g++ -o app *.cpp

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/app ./

EXPOSE 8080
CMD ["./app"]
"""

def generate_dockerfile(repo):
    languages = repo.get("languages", [])
    frameworks = repo.get("frameworks", [])
    name = repo["name"]
    
    if "python" in languages:
        return dockerfile_python(name, frameworks)
    elif any(l in languages for l in ["javascript", "typescript", "react", "vue"]):
        return dockerfile_node(name, frameworks)
    elif "rust" in languages:
        return dockerfile_rust(name)
    elif "go" in languages:
        return dockerfile_go(name)
    elif "c/c++" in languages:
        return dockerfile_cpp(name)
    else:
        return dockerfile_python(name, frameworks)

def main():
    print("=" * 60)
    print("AGENTFORGE: Auto-Generate Dockerfiles for Top Repos")
    print("=" * 60)
    
    audit = load_audit()
    repos = audit["repos"]
    
    # Sort by valuation descending, filter non-deployable
    top_non_deployable = sorted(
        [r for r in repos if not r.get("deployable", False)],
        key=lambda x: x.get("valuation", 0),
        reverse=True
    )[:50]
    
    generated = 0
    skipped = 0
    report_lines = []
    
    for repo in top_non_deployable:
        name = repo["name"]
        repo_path = REPOS_DIR / name
        dockerfile_path = repo_path / "Dockerfile"
        
        if not repo_path.exists():
            report_lines.append(f"SKIP: {name} - repo directory not found")
            skipped += 1
            continue
            
        if dockerfile_path.exists():
            report_lines.append(f"SKIP: {name} - Dockerfile already exists")
            skipped += 1
            continue
        
        df_content = generate_dockerfile(repo)
        try:
            with open(dockerfile_path, "w", encoding="utf-8") as f:
                f.write(df_content)
            generated += 1
            report_lines.append(f"OK:   {name} - Dockerfile generated ({', '.join(repo.get('languages', []))})")
        except Exception as e:
            report_lines.append(f"ERR:  {name} - {e}")
            skipped += 1
    
    # Write report
    report_path = Path("C:/temp/velvet-sojourner/audit/Dockerfile_Generation_Report.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("# Dockerfile Generation Report\\n\\n")
        f.write(f"**Date:** 2026-04-30\\n")
        f.write(f"**Target:** Top 50 non-deployable repos by valuation\\n")
        f.write(f"**Generated:** {generated}\\n")
        f.write(f"**Skipped:** {skipped}\\n\\n")
        f.write("## Results\\n\\n")
        for line in report_lines:
            f.write(line + "\\n")
    
    print(f"\\nComplete!")
    print(f"Generated: {generated} Dockerfiles")
    print(f"Skipped:   {skipped}")
    print(f"Report:    {report_path}")

if __name__ == "__main__":
    main()
